#!/bin/bash
if [ ! -e $1  ] ;then
touch $2 && echo "#!/bin/bash" > $1 && mv $1 $1.sh && vim $1.sh
else
        if [ ! -z $1 ];then
                fsl=`head -1 $1`
                case $fsl in
                "#!/bin/bash")
                        vim $1;;
                *)
                echo "error"
                exit 4 ;;
                esac
        else
                echo "#!/bin/bash" > $1
        fi
fi
